# Generated by Django 3.2.4 on 2021-06-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_auto_20210621_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='walker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walker', to='accounts.account'),
        ),
    ]
