# Generated by Django 3.2.4 on 2021-06-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210616_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(default='pets/pet_avatar_512_512.jpg', upload_to='pets/avatars/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='accounts/account_avatar_512_512.jpg', upload_to='accounts/avatars/'),
        ),
    ]
