# Generated by Django 3.2.4 on 2021-06-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210616_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(default='pets/pet_avatar_512_512.png', upload_to='pets/avatars/'),
        ),
    ]
