# Generated by Django 3.2.4 on 2021-06-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pet_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='account',
        ),
        migrations.AddField(
            model_name='pet',
            name='user_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.account'),
            preserve_default=False,
        ),
    ]
