# Generated by Django 3.2.4 on 2021-06-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210617_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user_account',
            new_name='owner',
        ),
    ]
