# Generated by Django 3.2.4 on 2021-06-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210618_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
