# Generated by Django 3.2.4 on 2021-06-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210617_1312'),
        ('outings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='pets',
            field=models.ManyToManyField(blank=True, to='accounts.Pet'),
        ),
    ]
